export const DEMO_BUILD_ID = 'demo-warden-guizzprints';

export const DEMO_BUILD = {
  id: DEMO_BUILD_ID,
  title: 'Warden Monument — Demonstração 3D',
  category: 'bedrock',
  subcategory: null,
  content_themes: ['Futurista'],
  content_categories: ['Estátuas e esculturas'],
  description: 'Modelo de demonstração do Guizzprints com 3.747 blocos. Inclui capa com quatro vistas, oito vistas PNG geradas pelo Guia 3D e uma amostra interativa com zoom e controle de camadas.',
  version: '1.21.0',
  file_size: '241 KB',
  price: 'Grátis',
  created_at: '2026-09-27T19:45:00.000Z',
  image_url_1: '/demo/warden/guide-view-01.png',
  image_url_2: '/demo/warden/guide-view-02.png',
  image_url_3: '/demo/warden/guide-view-03.png',
  image_url_4: '/demo/warden/guide-view-04.png',
  image_url_5: '/demo/warden/guide-view-05.png',
  image_url_6: '/demo/warden/guide-view-06.png',
  image_url_7: '/demo/warden/guide-view-07.png',
  image_url_8: '/demo/warden/guide-view-08.png',
  showcase_cover_url: '/demo/warden/four-views.png',
  youtube_trailer_url: '',
  spin_video_url: '/demo/warden/spin.webm',
  guide_schem_url: '/demo/warden/warden.schem?v=native-converter-20260928',
  guide_mcstructure_url: '/demo/warden/warden.mcstructure',
  studio_board_url: '/demo/warden/board.png',
  direct_download_url: '/demo/warden/warden.mcstructure',
  download_formats: [
    { id: 'holoprint', label: 'Holoprint', family: 'Bedrock' },
    { id: 'mcstructure', label: '.mcstructure', family: 'Bedrock', url: '/demo/warden/warden.mcstructure', fileName: 'warden-guizzprints.mcstructure' },
    { id: 'mcaddon', label: '.mcaddon', family: 'Bedrock' },
    { id: 'mcworld', label: '.mcworld', family: 'Bedrock' },
    { id: 'litematic', label: '.litematic', family: 'Java' },
    { id: 'schematic', label: '.schematic / .schem', family: 'Java', url: '/demo/warden/warden.schem', fileName: 'warden-guizzprints.schem' },
    { id: 'world', label: 'World', family: 'Java' },
    { id: 'mcfunction', label: '.mcfunction', family: 'Java' },
  ],
  downloads: 0,
  rating: 5,
  is_demo: true,
} as const;

export const DEMO_BUILD_SUMMARY = {
  id: DEMO_BUILD.id,
  title: DEMO_BUILD.title,
  category: DEMO_BUILD.category,
  subcategory: DEMO_BUILD.subcategory,
  content_themes: DEMO_BUILD.content_themes,
  content_categories: DEMO_BUILD.content_categories,
  image_url_1: DEMO_BUILD.showcase_cover_url || DEMO_BUILD.image_url_1,
  downloads: DEMO_BUILD.downloads,
  rating: DEMO_BUILD.rating,
};
