const pt = {
  metadata: 'Conheça o Guizz VIP: uma nova forma de apoiar o projeto. Planos, benefícios em preparação e tudo o que continua gratuito.',
  eyebrow: 'GUIZZ VIP', status: 'Em preparação', activeStatus: 'Acesso ativo',
  activeTitle: 'Seu acesso VIP está ativo', activeBody: 'Você já está navegando sem anúncios do Guizz e sem as etapas de espera do download.', activeUntil: 'Válido até', activeAccount: 'Gerenciar meu acesso', activeHeroNote: 'Seu acesso continua ativo enquanto você aproveita os benefícios.', activePlansNote: 'Você já tem acesso VIP. Estes planos ficam disponíveis para consultar outros períodos.',
  title: 'Seu apoio.', titleAccent: 'Um Guizz ainda melhor.',
  intro: 'Para quem encontra seu próximo mundo aqui e quer fazer parte do que vem depois.',
  heroNote: 'Conheça os planos. As assinaturas ainda não estão disponíveis.',
  explore: 'Conhecer os planos', freeLink: 'Continuar explorando',
  badgeLabel: 'APOIE O SEU PRÓXIMO MUNDO', badgeTitle: 'Guizz VIP',
  badgeText: 'Uma comunidade. Muitas possibilidades.', badgeFoot: 'Programa de apoiadores · em preparação',
  benefitsEyebrow: 'O QUE ESTAMOS PREPARANDO', benefitsTitle: 'Pequenos extras. Mais Guizz.',
  benefitsIntro: 'Benefícios previstos para o lançamento. Nada muda na sua conta por enquanto.',
  benefits: [
    { title: 'Guizz sem anúncios', body: 'Navegue pelo Guizz sem os anúncios exibidos pelo nosso site. Esse benefício não remove anúncios de sites externos.' },
    { title: 'Menos etapas para baixar', body: 'Vá ao destino do download sem a contagem de espera nem as etapas de anúncios do Guizz. A velocidade e as regras do site externo continuam as mesmas.' },
    { title: 'Seu selo de apoiador', body: 'Uma identificação VIP na sua conta para reconhecer quem faz parte desta próxima etapa.' },
  ],
  plansEyebrow: 'ESCOLHA SEU TEMPO', plansTitle: 'O mesmo VIP. No seu ritmo.',
  plansIntro: 'Todos os períodos terão os mesmos benefícios. Valores totais em reais, sem parcelas.',
  planNames: { daily: 'Diário', weekly: 'Semanal', monthly: 'Mensal' },
  days: 'dias', perDay: '/dia, aproximadamente', total: 'total pelo período',
  select: 'Ver plano', selected: 'Plano selecionado', periodBenefit: 'Mesmos benefícios VIP',
  plansNote: 'Pré-lançamento: você pode conferir os planos, mas nenhuma cobrança ou ativação é realizada nesta etapa.',
  summary: 'Seu plano Guizz VIP', summaryIntro: 'Confira os detalhes antes do lançamento.',
  period: 'Período', price: 'Valor total', paymentStatus: 'Pagamento ainda indisponível', returnNotice: 'Você voltou do checkout. O acesso VIP só é liberado após a confirmação do pagamento.',
  paymentNote: 'As assinaturas serão abertas quando o pagamento e os benefícios estiverem prontos. Você não será cobrado agora.',
  login: 'Preparar minha conta', loginNote: 'Entrar ou criar conta continua gratuito e não ativa uma assinatura.',
  accountLink: 'Ver minha conta',
  change: 'Voltar aos planos', close: 'Fechar resumo',
  freeEyebrow: 'O GUIZZ CONTINUA ABERTO', freeTitle: 'Seu catálogo de sempre. Gratuito.',
  freeIntro: 'O VIP será um apoio opcional. Explorar o Guizz não vai exigir uma assinatura.',
  freeItems: ['Explorar e pesquisar o catálogo', 'Favoritar e avaliar com sua conta', 'Navegar em português, inglês e espanhol'],
  installTitle: 'O Guizz, pertinho de você.', installBody: 'Adicione à tela inicial e abra o site como um app. Disponível também para quem não é VIP. É preciso estar conectado à internet.',
  accountTitle: 'Seu espaço VIP', accountIntro: 'Tudo sobre seu apoio, em um só lugar.',
  historyTitle: 'Pagamentos', historyBody: 'Quando as assinaturas forem abertas, esta será a área para acompanhar suas compras e o status do pagamento.',
  codeTitle: 'Códigos VIP', codeBody: 'O resgate de códigos estará disponível quando o programa for lançado.',
  soon: 'Disponível no lançamento', faqTitle: 'Antes de dar o próximo passo.', faqEyebrow: 'PERGUNTAS FREQUENTES',
  faq: [
    { q: 'Preciso de VIP para usar o Guizz?', a: 'Não. O catálogo continua aberto. Favoritos e avaliações seguem disponíveis gratuitamente com sua conta.' },
    { q: 'Quais anúncios o VIP remove?', a: 'O benefício previsto remove os anúncios exibidos pelo Guizz, incluindo as etapas de anúncios do nosso fluxo de download. Não se aplica a anúncios em sites externos.' },
    { q: 'O que muda nos downloads?', a: 'O VIP terá acesso ao destino do download sem a contagem de espera nem as etapas de anúncios do Guizz. Isso não aumenta a velocidade de transferência nem remove etapas ou anúncios do site externo que hospeda o arquivo. O benefício ainda está em preparação.' },
    { q: 'Posso assinar agora?', a: 'Ainda não. Os preços já estão definidos, mas o pagamento e a ativação dos benefícios estão em preparação. Nenhum plano selecionado aqui gera uma cobrança.' },
    { q: 'O plano renova automaticamente?', a: 'Nenhuma assinatura está ativa nesta etapa. As condições de renovação, início e cancelamento serão apresentadas antes de qualquer compra no lançamento.' },
    { q: 'Vai funcionar no celular?', a: 'Sim. A página foi feita para celular e computador. Adicionar o Guizz à tela inicial será gratuito; o catálogo e os downloads continuam precisando de internet.' },
  ],
  contactTitle: 'Ficou alguma dúvida?', contact: 'Fale com o Guizz',
};

type VipCopy = typeof pt;
const en: VipCopy = {
  accountLink: 'View my account', activeStatus: 'Access active', activeTitle: 'Your VIP access is active', activeBody: 'You are browsing without Guizz ads and without the download waiting steps.', activeUntil: 'Valid until', activeAccount: 'Manage my access', activeHeroNote: 'Your access remains active while you enjoy the benefits.', activePlansNote: 'You already have VIP access. These plans are here if you want to compare other periods.',
  metadata: 'Meet Guizz VIP: a new way to support the project. Explore plans, upcoming benefits and everything that stays free.',
  eyebrow: 'GUIZZ VIP', status: 'Coming soon', title: 'Your support.', titleAccent: 'An even better Guizz.',
  intro: 'For everyone who finds their next world here and wants to be part of what comes next.',
  heroNote: 'Explore the plans. Subscriptions are not available yet.', explore: 'Explore the plans', freeLink: 'Keep exploring',
  badgeLabel: 'SUPPORT YOUR NEXT WORLD', badgeTitle: 'Guizz VIP', badgeText: 'One community. Many possibilities.', badgeFoot: 'Supporter program · coming soon',
  benefitsEyebrow: 'WHAT WE ARE PREPARING', benefitsTitle: 'Little extras. More Guizz.', benefitsIntro: 'Benefits planned for launch. Nothing changes in your account yet.',
  benefits: [
    { title: 'Ad-free Guizz', body: 'Browse Guizz without ads displayed by our site. This benefit does not remove ads on external websites.' },
    { title: 'Fewer steps to download', body: 'Reach the download destination without Guizz’s countdown or ad steps. The external site’s speed and rules still apply.' },
    { title: 'Your supporter badge', body: 'A VIP badge on your account to recognize those who are part of this next chapter.' },
  ],
  plansEyebrow: 'CHOOSE YOUR TIME', plansTitle: 'The same VIP. At your pace.', plansIntro: 'Every period will include the same benefits. Full prices in Brazilian reais, no installments.',
  planNames: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' },
  days: 'days', perDay: '/day, approximately', total: 'total for the period', select: 'View plan', selected: 'Selected plan', periodBenefit: 'Same VIP benefits',
  plansNote: 'Pre-launch: you can explore the plans, but no payment or activation takes place at this stage.',
  summary: 'Your Guizz VIP plan', summaryIntro: 'Review the details ahead of launch.', period: 'Period', price: 'Total price', paymentStatus: 'Payments are not available yet', returnNotice: 'You returned from checkout. VIP access is released only after payment is confirmed.',
  paymentNote: 'Subscriptions will open when payments and benefits are ready. You will not be charged now.', login: 'Prepare my account', loginNote: 'Signing in or creating an account is free and does not activate a subscription.', change: 'Back to plans', close: 'Close summary',
  freeEyebrow: 'GUIZZ STAYS OPEN', freeTitle: 'Your usual catalog. Still free.', freeIntro: 'VIP will be an optional way to support us. Exploring Guizz will not require a subscription.',
  freeItems: ['Browse and search the catalog', 'Save favorites and rate with your account', 'Browse in English, Portuguese and Spanish'],
  installTitle: 'Keep Guizz close.', installBody: 'Add it to your home screen and open the site like an app. Available without VIP, too. An internet connection is required.',
  accountTitle: 'Your VIP space', accountIntro: 'Everything about your support, in one place.',
  historyTitle: 'Payments', historyBody: 'When subscriptions open, this will be the place to track your purchases and payment status.',
  codeTitle: 'VIP codes', codeBody: 'Code redemption will be available when the program launches.', soon: 'Available at launch',
  faqTitle: 'Before your next step.', faqEyebrow: 'FREQUENTLY ASKED QUESTIONS',
  faq: [
    { q: 'Do I need VIP to use Guizz?', a: 'No. The catalog stays open. Favorites and ratings remain free with your account.' },
    { q: 'Which ads does VIP remove?', a: 'The planned benefit removes ads displayed by Guizz, including ad steps in our download flow. It does not apply to ads on external websites.' },
    { q: 'What changes for downloads?', a: 'VIP will let you reach the download destination without Guizz’s countdown or ad steps. This does not increase transfer speeds or remove steps or ads from the external file-hosting site. This benefit is still being prepared.' },
    { q: 'Can I subscribe now?', a: 'Not yet. Prices are set, but payments and benefit activation are still being prepared. Selecting a plan here does not create a charge.' },
    { q: 'Does the plan renew automatically?', a: 'No subscription is active at this stage. Renewal, start date and cancellation terms will be shown before any purchase at launch.' },
    { q: 'Will it work on my phone?', a: 'Yes. This page is designed for phones and computers. Adding Guizz to your home screen will be free; the catalog and downloads still require internet access.' },
  ], contactTitle: 'Have a question?', contact: 'Contact Guizz',
};
const es: VipCopy = {
  accountLink: 'Ver mi cuenta',
  metadata: 'Conoce Guizz VIP: una nueva forma de apoyar el proyecto. Planes, beneficios en preparación y todo lo que sigue siendo gratis.',
  eyebrow: 'GUIZZ VIP', status: 'En preparación', activeStatus: 'Acceso activo', activeTitle: 'Tu acceso VIP está activo', activeBody: 'Ya navegas sin anuncios de Guizz y sin las etapas de espera de la descarga.', activeUntil: 'Válido hasta', activeAccount: 'Gestionar mi acceso', activeHeroNote: 'Tu acceso sigue activo mientras disfrutas de los beneficios.', activePlansNote: 'Ya tienes acceso VIP. Estos planes quedan disponibles para comparar otros períodos.', title: 'Tu apoyo.', titleAccent: 'Un Guizz aún mejor.',
  intro: 'Para quienes encuentran su próximo mundo aquí y quieren ser parte de lo que viene.',
  heroNote: 'Conoce los planes. Las suscripciones aún no están disponibles.', explore: 'Conocer los planes', freeLink: 'Seguir explorando',
  badgeLabel: 'APOYA TU PRÓXIMO MUNDO', badgeTitle: 'Guizz VIP', badgeText: 'Una comunidad. Muchas posibilidades.', badgeFoot: 'Programa de colaboradores · en preparación',
  benefitsEyebrow: 'LO QUE ESTAMOS PREPARANDO', benefitsTitle: 'Pequeños extras. Más Guizz.', benefitsIntro: 'Beneficios previstos para el lanzamiento. Tu cuenta aún no cambia.',
  benefits: [
    { title: 'Guizz sin anuncios', body: 'Navega por Guizz sin los anuncios de nuestro sitio. Este beneficio no elimina anuncios de sitios externos.' },
    { title: 'Menos pasos para descargar', body: 'Llega al destino de descarga sin la cuenta atrás ni los pasos con anuncios de Guizz. La velocidad y las reglas del sitio externo siguen siendo las mismas.' },
    { title: 'Tu insignia de colaborador', body: 'Una identificación VIP en tu cuenta para reconocer a quienes forman parte de esta próxima etapa.' },
  ],
  plansEyebrow: 'ELIGE TU TIEMPO', plansTitle: 'El mismo VIP. A tu ritmo.', plansIntro: 'Todos los períodos tendrán los mismos beneficios. Precios totales en reales brasileños, sin cuotas.',
  planNames: { daily: 'Diario', weekly: 'Semanal', monthly: 'Mensual' },
  days: 'días', perDay: '/día, aproximadamente', total: 'total por el período', select: 'Ver plan', selected: 'Plan seleccionado', periodBenefit: 'Mismos beneficios VIP',
  plansNote: 'Prelanzamiento: puedes consultar los planes, pero no se realiza ningún cobro ni activación en esta etapa.',
  summary: 'Tu plan Guizz VIP', summaryIntro: 'Revisa los detalles antes del lanzamiento.', period: 'Período', price: 'Precio total', paymentStatus: 'Pagos aún no disponibles', returnNotice: 'Volviste del checkout. El acceso VIP se libera solo después de confirmar el pago.',
  paymentNote: 'Las suscripciones se abrirán cuando el pago y los beneficios estén listos. No se te cobrará ahora.', login: 'Preparar mi cuenta', loginNote: 'Iniciar sesión o crear una cuenta es gratis y no activa una suscripción.', change: 'Volver a los planes', close: 'Cerrar resumen',
  freeEyebrow: 'GUIZZ SIGUE ABIERTO', freeTitle: 'Tu catálogo de siempre. Gratis.', freeIntro: 'VIP será un apoyo opcional. Explorar Guizz no requerirá una suscripción.',
  freeItems: ['Explorar y buscar en el catálogo', 'Guardar favoritos y valorar con tu cuenta', 'Navegar en español, inglés y portugués'],
  installTitle: 'Guizz, siempre cerca.', installBody: 'Añádelo a la pantalla de inicio y abre el sitio como una app. También disponible sin VIP. Se necesita conexión a internet.',
  accountTitle: 'Tu espacio VIP', accountIntro: 'Todo sobre tu apoyo, en un solo lugar.',
  historyTitle: 'Pagos', historyBody: 'Cuando se abran las suscripciones, aquí podrás consultar tus compras y el estado del pago.',
  codeTitle: 'Códigos VIP', codeBody: 'El canje de códigos estará disponible cuando se lance el programa.', soon: 'Disponible en el lanzamiento',
  faqTitle: 'Antes del siguiente paso.', faqEyebrow: 'PREGUNTAS FRECUENTES',
  faq: [
    { q: '¿Necesito VIP para usar Guizz?', a: 'No. El catálogo sigue abierto. Los favoritos y las valoraciones siguen siendo gratuitos con tu cuenta.' },
    { q: '¿Qué anuncios elimina VIP?', a: 'El beneficio previsto elimina los anuncios de Guizz, incluidos los pasos con anuncios de nuestro flujo de descarga. No se aplica a los anuncios de sitios externos.' },
    { q: '¿Qué cambia en las descargas?', a: 'VIP permitirá llegar al destino de descarga sin la cuenta atrás ni los pasos con anuncios de Guizz. Esto no aumenta la velocidad de transferencia ni elimina pasos o anuncios del sitio externo que aloja el archivo. El beneficio aún está en preparación.' },
    { q: '¿Puedo suscribirme ahora?', a: 'Todavía no. Los precios están definidos, pero el pago y la activación de beneficios están en preparación. Seleccionar un plan aquí no genera un cobro.' },
    { q: '¿El plan se renueva automáticamente?', a: 'No hay ninguna suscripción activa en esta etapa. Las condiciones de renovación, inicio y cancelación se mostrarán antes de cualquier compra en el lanzamiento.' },
    { q: '¿Funcionará en el móvil?', a: 'Sí. Esta página está diseñada para móviles y ordenadores. Añadir Guizz a la pantalla de inicio será gratis; el catálogo y las descargas siguen necesitando internet.' },
  ], contactTitle: '¿Tienes alguna pregunta?', contact: 'Contacta con Guizz',
};

type VipCopyMode = 'prelaunch' | 'live';

function liveCopy(base: VipCopy, locale: string): VipCopy {
  if (locale === 'pt') {
    return {
      ...base,
      metadata: 'Conheça o Guizz VIP: planos flexíveis, pagamento PIX seguro e acesso sem anúncios do Guizz após a confirmação.',
      status: 'Disponível agora',
      heroNote: 'Escolha um plano e continue para o pagamento PIX seguro.',
      badgeFoot: 'Programa de apoiadores · disponível agora',
      benefitsEyebrow: 'BENEFÍCIOS DO GUIZZ VIP',
      benefitsIntro: 'O acesso VIP é liberado pela confirmação server-side do pagamento.',
      plansNote: 'Escolha um período e continue para o checkout seguro do Mercado Pago.',
      summaryIntro: 'Confira os detalhes e continue para o pagamento seguro.',
      paymentStatus: 'Pagamento PIX seguro',
      paymentNote: 'Você será levado ao checkout seguro do Mercado Pago. O VIP é ativado somente após a confirmação do pagamento.',
      freeIntro: 'O VIP é um apoio opcional. Explorar o Guizz não exige uma assinatura.',
      historyBody: 'Acompanhe suas compras e o status do pagamento nesta área.',
      soon: 'Disponível',
      faqTitle: 'Antes de confirmar seu pagamento.',
      faq: [
        base.faq[0],
        { ...base.faq[1], a: 'O VIP remove os anúncios exibidos pelo Guizz, incluindo as etapas de anúncios do nosso fluxo de download. Não se aplica a anúncios de sites externos.' },
        { ...base.faq[2], a: 'O VIP leva você ao destino do download sem a contagem de espera nem as etapas de anúncios do Guizz. A velocidade e as regras do site externo continuam as mesmas.' },
        { q: 'Posso assinar agora?', a: 'Sim. Escolha um plano, entre na sua conta e conclua o pagamento PIX. O VIP é ativado após a confirmação.' },
        { q: 'O plano renova automaticamente?', a: 'Não. Os planos são compras avulsas pelo período escolhido, sem renovação automática.' },
        base.faq[5],
      ],
    };
  }
  if (locale === 'es') {
    return {
      ...base,
      metadata: 'Conoce Guizz VIP: planes flexibles, pago PIX seguro y acceso sin anuncios de Guizz tras la confirmación.',
      status: 'Disponible ahora',
      heroNote: 'Elige un plan y continúa al pago PIX seguro.',
      badgeFoot: 'Programa de colaboradores · disponible ahora',
      benefitsEyebrow: 'BENEFICIOS DE GUIZZ VIP',
      benefitsIntro: 'El acceso VIP se libera tras la confirmación server-side del pago.',
      plansNote: 'Elige un período y continúa al checkout seguro de Mercado Pago.',
      summaryIntro: 'Revisa los detalles y continúa al pago seguro.',
      paymentStatus: 'Pago PIX seguro',
      paymentNote: 'Continuarás al checkout seguro de Mercado Pago. VIP se activa solo después de confirmar el pago.',
      freeIntro: 'VIP es un apoyo opcional. Explorar Guizz no requiere una suscripción.',
      historyBody: 'Consulta aquí tus compras y el estado del pago.',
      soon: 'Disponible',
      faqTitle: 'Antes de confirmar tu pago.',
      faq: [
        base.faq[0],
        { ...base.faq[1], a: 'VIP elimina los anuncios de Guizz, incluidos los pasos con anuncios de nuestro flujo de descarga. No se aplica a anuncios de sitios externos.' },
        { ...base.faq[2], a: 'VIP te lleva al destino de descarga sin la cuenta atrás ni los pasos con anuncios de Guizz. La velocidad y las reglas del sitio externo siguen siendo las mismas.' },
        { q: '¿Puedo suscribirme ahora?', a: 'Sí. Elige un plan, inicia sesión y completa el pago PIX. VIP se activa tras la confirmación.' },
        { q: '¿El plan se renueva automáticamente?', a: 'No. Los planes son compras únicas por el período elegido, sin renovación automática.' },
        base.faq[5],
      ],
    };
  }
  return {
    ...base,
    metadata: 'Meet Guizz VIP: flexible plans, secure PIX payment and an ad-free Guizz experience after confirmation.',
    status: 'Available now',
    heroNote: 'Choose a plan and continue to secure PIX payment.',
    badgeFoot: 'Supporter program · available now',
    benefitsEyebrow: 'GUIZZ VIP BENEFITS',
    benefitsIntro: 'VIP access is released after server-side payment confirmation.',
    plansNote: 'Choose a period and continue to Mercado Pago’s secure checkout.',
    summaryIntro: 'Review the details and continue to secure payment.',
    paymentStatus: 'Secure PIX payment',
    paymentNote: 'You will continue to Mercado Pago’s secure checkout. VIP activates only after payment is confirmed.',
    freeIntro: 'VIP is optional support. Exploring Guizz does not require a subscription.',
    historyBody: 'Track your purchases and payment status here.',
    soon: 'Available',
    faqTitle: 'Before you confirm your payment.',
    faq: [
      base.faq[0],
      { ...base.faq[1], a: 'VIP removes ads displayed by Guizz, including ad steps in our download flow. It does not apply to ads on external websites.' },
      { ...base.faq[2], a: 'VIP takes you to the download destination without Guizz’s countdown or ad steps. The external site’s speed and rules still apply.' },
      { q: 'Can I subscribe now?', a: 'Yes. Choose a plan, sign in and complete the PIX payment. VIP activates after confirmation.' },
      { q: 'Does the plan renew automatically?', a: 'No. Plans are one-time purchases for the selected period, with no automatic renewal.' },
      base.faq[5],
    ],
  };
}

export function getVipCopy(locale: string, mode: VipCopyMode = 'prelaunch'): VipCopy {
  const base = locale === 'pt' ? pt : locale === 'es' ? es : en;
  return mode === 'live' ? liveCopy(base, locale) : base;
}
